# fly.toml app configuration file generated for blog-app-frontend on 2024-11-06T13:37:30+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'blog-app-frontend'
primary_region = 'cdg'

[build]

[http_service]
internal_port = 80  # Ensure this matches the port Angular uses to serve
force_https = true
auto_stop_machines = 'off'
auto_start_machines = false
min_machines_running = 0
processes = ['app']

[[services]]
internal_port = 80
processes = ["app"]
protocol = "tcp"

[[services.http_checks]]
grace_period = "5s"
interval = "15s"
method = "GET"
path = "/"  # Root path or another valid route in your app
protocol = "http"
timeout = "5s"

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
