# fly.toml app configuration file generated for blog-app-black-pine-3535 on 2024-10-31T12:45:04+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.


app = 'blog-app-black-pine-3535'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[services]]
  processes = ["app"]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
