name: Deploy Angular App

on:
  push:
    branches: [ main ]

permissions:
  contents: write

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify frontend directory exists
        run: |
          ls -l ./frontend
          # This will help to debug if the frontend directory exists

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies and Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: build-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify frontend directory exists
        run: |
          ls -l ./frontend
          # This ensures that the frontend folder exists before deploying

      - name: Set up Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Angular Application
        working-directory: ./frontend  # Ensure we are in the correct folder
        run: |
          flyctl deploy --remote-only